# Generated by Django 4.1.4 on 2023-01-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bendungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_bendungan', models.CharField(max_length=100)),
                ('lk_bendungan', models.CharField(max_length=100)),
                ('luas_bendungan', models.CharField(max_length=100)),
                ('vlm_bendungan', models.CharField(max_length=100)),
            ],
        ),
    ]
